# Generated by Django 4.2.13 on 2024-05-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0003_dependant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependant',
            name='depandantName',
            field=models.TextField(),
        ),
    ]
