# Generated by Django 4.2.13 on 2024-05-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0004_alter_dependant_depandantname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependant',
            options={'ordering': ('created',)},
        ),
    ]
