# Generated by Django 4.2.13 on 2024-05-15 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0006_alter_dependant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('overviewHealthStatus', models.CharField(max_length=10)),
                ('overviewRiskScore', models.IntegerField()),
                ('overviewHealthGoals', models.TextField()),
                ('overViewBloodGroup', models.CharField(max_length=3)),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioData.member')),
            ],
        ),
    ]
