# Generated by Django 4.2.13 on 2024-05-17 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0011_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='memberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='BioData.member'),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='memberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergy', to='BioData.member'),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='dependantId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependants', to='BioData.member'),
        ),
        migrations.AlterField(
            model_name='othernote',
            name='memberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='othernote', to='BioData.member'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='memberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overview', to='BioData.member'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='memberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery', to='BioData.member'),
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('socialNotes', models.CharField(max_length=20)),
                ('atriskDueTo', models.CharField(max_length=50)),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioData.member')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('familyRelationship', models.CharField(max_length=20)),
                ('familyCondition', models.CharField(max_length=50)),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='BioData.member')),
            ],
        ),
    ]
