# Generated by Django 5.0.6 on 2024-06-25 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0012_alter_admission_memberid_alter_allergy_memberid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='memberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='BioData.member'),
        ),
    ]
