# Generated by Django 5.0.6 on 2024-06-26 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0013_alter_social_memberid'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(blank=True, max_length=20, null=True)),
                ('updatedBy', models.EmailField(max_length=254)),
                ('channelDirection', models.CharField(blank=True, max_length=20, null=True)),
                ('interactionDetails', models.TextField()),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction', to='BioData.member')),
            ],
        ),
    ]
