# Generated by Django 5.0.6 on 2024-06-26 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0014_interactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updatedBy', models.EmailField(max_length=254)),
                ('notes', models.TextField()),
                ('readingDate', models.DateField()),
                ('systolic', models.IntegerField()),
                ('diastolic', models.IntegerField()),
                ('pulse', models.IntegerField()),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloodpressure', to='BioData.member')),
            ],
        ),
        migrations.CreateModel(
            name='Oxygen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updatedBy', models.EmailField(max_length=254)),
                ('notes', models.TextField()),
                ('readingDate', models.DateField()),
                ('oxygen', models.IntegerField()),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oxygen', to='BioData.member')),
            ],
        ),
        migrations.CreateModel(
            name='PulseRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updatedBy', models.EmailField(max_length=254)),
                ('notes', models.TextField()),
                ('readingDate', models.DateField()),
                ('pulse', models.IntegerField()),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulse', to='BioData.member')),
            ],
        ),
        migrations.CreateModel(
            name='RespiratoryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updatedBy', models.EmailField(max_length=254)),
                ('notes', models.TextField()),
                ('readingDate', models.DateField()),
                ('respiratory', models.IntegerField()),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respiratory', to='BioData.member')),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updatedBy', models.EmailField(max_length=254)),
                ('notes', models.TextField()),
                ('readingDate', models.DateField()),
                ('temperature', models.IntegerField()),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature', to='BioData.member')),
            ],
        ),
    ]
