# Generated by Django 5.0.6 on 2024-06-26 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0015_bloodpressure_oxygen_pulserate_respiratoryrate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMassIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updatedBy', models.EmailField(max_length=254)),
                ('readingDate', models.DateField()),
                ('bmi', models.IntegerField()),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bmi', to='BioData.member')),
            ],
        ),
        migrations.CreateModel(
            name='FastingBloodSugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updatedBy', models.EmailField(max_length=254)),
                ('readingDate', models.DateField()),
                ('fbs', models.IntegerField()),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbs', to='BioData.member')),
            ],
        ),
        migrations.CreateModel(
            name='GlycatedHaemoglobin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updatedBy', models.EmailField(max_length=254)),
                ('readingDate', models.DateField()),
                ('hba1c', models.IntegerField()),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hba1c', to='BioData.member')),
            ],
        ),
        migrations.CreateModel(
            name='RandomBloodSugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updatedBy', models.EmailField(max_length=254)),
                ('readingDate', models.DateField()),
                ('rbs', models.IntegerField()),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rbs', to='BioData.member')),
            ],
        ),
    ]
