# Generated by Django 5.0.6 on 2024-06-27 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0016_bodymassindex_fastingbloodsugar_glycatedhaemoglobin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('condition', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=100)),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='BioData.member')),
            ],
        ),
    ]
