# Generated by Django 5.0.6 on 2024-06-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0017_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodpressure',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='oxygen',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='pulserate',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='respiratoryrate',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='notes',
        ),
    ]
