# Generated by Django 5.0.6 on 2024-06-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0018_remove_bloodpressure_notes_remove_oxygen_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodpressure',
            name='pulse',
        ),
    ]
