# Generated by Django 5.0.6 on 2024-06-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0019_remove_bloodpressure_pulse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymassindex',
            name='bmi',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
