# Generated by Django 5.0.6 on 2024-06-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0021_alter_bodymassindex_bmi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodymassindex',
            name='bmi',
        ),
        migrations.AddField(
            model_name='bodymassindex',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bodymassindex',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
