# Generated by Django 5.0.6 on 2024-06-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0022_remove_bodymassindex_bmi_bodymassindex_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glycatedhaemoglobin',
            name='hba1c',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
