# Generated by Django 5.0.6 on 2024-06-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0024_alter_fastingbloodsugar_fbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oxygen',
            name='oxygen',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pulserate',
            name='pulse',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='respiratoryrate',
            name='respiratory',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
