# Generated by Django 5.0.6 on 2024-06-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0025_alter_oxygen_oxygen_alter_pulserate_pulse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressure',
            name='diastolic',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='systolic',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
