# Generated by Django 5.0.6 on 2024-07-03 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0026_alter_bloodpressure_diastolic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='memberJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enrollmentDate', models.DateField()),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='BioData.member')),
            ],
        ),
    ]
