# Generated by Django 5.0.6 on 2024-07-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0027_memberjourney'),
    ]

    operations = [
        migrations.DeleteModel(
            name='memberJourney',
        ),
    ]
