# Generated by Django 5.0.6 on 2024-07-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0029_callmembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callmembers',
            name='department',
            field=models.CharField(default='Care Manager', max_length=20),
        ),
        migrations.AlterField(
            model_name='callmembers',
            name='status',
            field=models.CharField(default='Not started', max_length=20),
        ),
    ]
