# Generated by Django 5.0.6 on 2024-07-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0031_completeonboarding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='completeOnboarding',
        ),
    ]
