# Generated by Django 5.0.6 on 2024-07-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0036_addlabresults_doctorssecondconsultation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('taskName', models.CharField(max_length=50)),
                ('taskDescription', models.TextField()),
                ('taskDueDate', models.DateField()),
                ('taskStatus', models.CharField(max_length=20)),
                ('taskAssignedTo', models.CharField(max_length=50)),
            ],
        ),
    ]
