# Generated by Django 5.0.6 on 2024-07-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0038_task_taskdepartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taskDescription',
            new_name='task',
        ),
    ]
