# Generated by Django 5.0.6 on 2024-07-30 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0039_rename_taskdescription_task_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='memberId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BioData.member'),
            preserve_default=False,
        ),
    ]
