# Generated by Django 5.0.6 on 2024-08-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0040_task_memberid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskDueDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
