# Generated by Django 5.0.6 on 2024-08-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0041_alter_task_taskduedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskDueDate',
            field=models.CharField(default='22/07', max_length=20),
            preserve_default=False,
        ),
    ]
