# Generated by Django 5.0.6 on 2024-08-08 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0044_alter_bloodpressure_readingdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callmembers',
            name='memberId',
        ),
        migrations.RemoveField(
            model_name='collectandsubmitvitals',
            name='memberId',
        ),
        migrations.RemoveField(
            model_name='completeonboarding',
            name='memberId',
        ),
        migrations.RemoveField(
            model_name='doctorssecondconsultation',
            name='memberId',
        ),
        migrations.RemoveField(
            model_name='generatecareplan',
            name='memberId',
        ),
        migrations.RemoveField(
            model_name='generatelabrequest',
            name='memberId',
        ),
        migrations.RemoveField(
            model_name='initialconsultationdoctor',
            name='memberId',
        ),
        migrations.RemoveField(
            model_name='initialconsultationnutritionist',
            name='memberId',
        ),
        migrations.RemoveField(
            model_name='initialconsultationpsychologist',
            name='memberId',
        ),
        migrations.RemoveField(
            model_name='initialmentalhealthscreening',
            name='memberId',
        ),
        migrations.RemoveField(
            model_name='scheduleannuallabtest',
            name='memberId',
        ),
        migrations.RemoveField(
            model_name='scheduleresultsreview',
            name='memberId',
        ),
        migrations.RemoveField(
            model_name='schedulevitalscollection',
            name='memberId',
        ),
        migrations.AlterField(
            model_name='bodymassindex',
            name='readingDate',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='memberTaskBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('taskDate', models.DateField()),
                ('status', models.CharField(default='Not started', max_length=20)),
                ('department', models.CharField(blank=True, max_length=20, null=True)),
                ('assignedTo', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioData.member')),
            ],
        ),
        migrations.DeleteModel(
            name='AddLabResults',
        ),
        migrations.DeleteModel(
            name='callMembers',
        ),
        migrations.DeleteModel(
            name='CollectandSubmitVitals',
        ),
        migrations.DeleteModel(
            name='CompleteOnboarding',
        ),
        migrations.DeleteModel(
            name='DoctorsSecondConsultation',
        ),
        migrations.DeleteModel(
            name='GenerateCarePlan',
        ),
        migrations.DeleteModel(
            name='GenerateLabRequest',
        ),
        migrations.DeleteModel(
            name='InitialConsultationDoctor',
        ),
        migrations.DeleteModel(
            name='InitialConsultationNutritionist',
        ),
        migrations.DeleteModel(
            name='InitialConsultationPsychologist',
        ),
        migrations.DeleteModel(
            name='InitialMentalHealthScreening',
        ),
        migrations.DeleteModel(
            name='ScheduleAnnualLabTest',
        ),
        migrations.DeleteModel(
            name='ScheduleResultsReview',
        ),
        migrations.DeleteModel(
            name='ScheduleVitalsCollection',
        ),
    ]
