# Generated by Django 5.0.6 on 2024-08-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0045_remove_callmembers_memberid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membertaskbase',
            name='task',
            field=models.TextField(default='nn'),
            preserve_default=False,
        ),
    ]
