# Generated by Django 5.0.6 on 2024-08-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0046_membertaskbase_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='membertaskbase',
            name='notesBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='membertaskbase',
            name='notesDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
