# Generated by Django 5.0.6 on 2024-08-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0047_membertaskbase_notesby_membertaskbase_notesdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membertaskbase',
            name='notesBy',
            field=models.EmailField(default='mm@g.com', max_length=254),
            preserve_default=False,
        ),
    ]
