# Generated by Django 5.0.6 on 2024-08-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0048_alter_membertaskbase_notesby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memberDelivery',
            field=models.TextField(blank=True, null=True),
        ),
    ]
