# Generated by Django 5.0.6 on 2024-08-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0049_alter_member_memberdelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memberDOB',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='memberGender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='memerEmail',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
