# Generated by Django 5.0.6 on 2024-08-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0050_alter_member_memberdob_alter_member_membergender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodpressure',
            name='interpretation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
