# Generated by Django 5.0.6 on 2024-08-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0051_bloodpressure_interpretation'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='interpretation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
