# Generated by Django 5.0.6 on 2024-08-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0052_temperature_interpretation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='readingDate',
            field=models.CharField(max_length=50),
        ),
    ]
