# Generated by Django 5.0.6 on 2024-08-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0054_oxygen_interpretation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oxygen',
            name='readingDate',
            field=models.CharField(max_length=50),
        ),
    ]
