# Generated by Django 5.0.6 on 2024-08-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0055_alter_oxygen_readingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oxygen',
            name='readingDate',
            field=models.CharField(max_length=100),
        ),
    ]
