# Generated by Django 5.0.6 on 2024-08-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0059_randombloodsugar_interpretation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastingbloodsugar',
            name='interpretation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fastingbloodsugar',
            name='readingDate',
            field=models.CharField(max_length=100),
        ),
    ]
