# Generated by Django 5.0.6 on 2024-08-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0062_bodymassindex_interpretation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('HRTasks', models.IntegerField()),
                ('HREmail', models.EmailField(max_length=254)),
                ('HRDepartment', models.CharField(max_length=50)),
            ],
        ),
    ]
