# Generated by Django 5.0.6 on 2024-08-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0063_humanresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanresource',
            name='HRTasks',
            field=models.IntegerField(default=0),
        ),
    ]
