# Generated by Django 5.0.6 on 2024-08-21 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0064_alter_humanresource_hrtasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('appointmentDate', models.CharField(max_length=100)),
                ('appointmentTime', models.CharField(max_length=50)),
                ('appointmentReason', models.CharField(max_length=50)),
                ('appointmentDepartment', models.CharField(max_length=50)),
                ('appointmentCreatedBy', models.EmailField(max_length=254)),
                ('appointmentStatus', models.CharField(default='Not started', max_length=50)),
                ('appointmentAssignedTo', models.CharField(blank=True, max_length=50, null=True)),
                ('appointmentNotes', models.TextField(blank=True, null=True)),
                ('appointmentNotesDate', models.CharField(blank=True, max_length=50, null=True)),
                ('appointmentNotesBy', models.EmailField(blank=True, max_length=254, null=True)),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioData.member')),
            ],
        ),
    ]
