# Generated by Django 5.0.6 on 2024-08-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0067_task_taskappointmentid_alter_task_taskstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskStatus',
            field=models.CharField(max_length=20),
        ),
    ]
