# Generated by Django 5.0.6 on 2024-08-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0069_humanresource_hrrole_humanresource_hrstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskAssignedTo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
