# Generated by Django 5.0.6 on 2024-08-24 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0072_remove_humanresource_hrdepartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskAssignedTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskAssignedTo', to='BioData.humanresource'),
        ),
    ]
