# Generated by Django 5.0.6 on 2024-08-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0076_remove_humanresource_hrdepartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanresource',
            name='HRRole',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Psychologist', 'Psychologist'), ('Nutritionist', 'Nutritionist'), ('Care Manager', 'Care Manager'), ('Engagement Lead', 'Engagement Lead')], default='Care Manager', max_length=50),
        ),
    ]
