# Generated by Django 5.0.6 on 2024-08-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0077_alter_humanresource_hrrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='taskDepartment',
        ),
    ]
