# Generated by Django 5.0.6 on 2024-08-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0078_remove_task_taskdepartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humanresource',
            name='TaskId',
        ),
    ]
