# Generated by Django 5.0.6 on 2024-08-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0079_remove_humanresource_taskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskAssignedTo',
            field=models.EmailField(default='machayoephraim@gmail.com', max_length=254),
        ),
    ]
