# Generated by Django 5.0.6 on 2024-08-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0080_alter_task_taskassignedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memberCareManager',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='memberEngagementLead',
            field=models.EmailField(max_length=254),
        ),
    ]
