# Generated by Django 5.0.6 on 2024-08-26 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0081_alter_member_membercaremanager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointmentAssignedTo',
            field=models.EmailField(default='machayoephraim@gmail.com', max_length=254),
        ),
        migrations.CreateModel(
            name='Whatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('messageStatus', models.CharField(choices=[('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Read', 'Read')], default='Sent', max_length=50)),
                ('messageFrom', models.EmailField(max_length=254)),
                ('messageTo', models.CharField(max_length=20)),
                ('messageDirection', models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound')], max_length=50)),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioData.member')),
            ],
        ),
    ]
