# Generated by Django 5.0.6 on 2024-08-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0083_alter_whatsapp_messagefrom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapp',
            name='messageStatus',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Read', 'Read'), ('Received', 'Received')], default='Sent', max_length=50),
        ),
    ]
