# Generated by Django 5.0.6 on 2024-08-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0084_alter_whatsapp_messagestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapp',
            name='messageStatus',
            field=models.CharField(choices=[('sent', 'sent'), ('delivered', 'delivered'), ('read', 'read'), ('received', 'received')], default='Sent', max_length=50),
        ),
    ]
