# Generated by Django 5.0.6 on 2024-09-01 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0087_alter_social_socialnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionlog',
            name='taskId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskId', to='BioData.task'),
        ),
    ]
