# Generated by Django 5.0.6 on 2024-09-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0088_interactionlog_taskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memberNutritionist',
            field=models.EmailField(max_length=254),
        ),
    ]
