# Generated by Django 5.0.6 on 2024-09-03 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0089_alter_member_membernutritionist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('prescriptionDrug', models.CharField(max_length=50)),
                ('prescriptionDate', models.CharField(max_length=50)),
                ('prescriptionDosage', models.IntegerField()),
                ('prescriptionFrequency', models.IntegerField()),
                ('prescriptionDuration', models.IntegerField()),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioData.member')),
            ],
        ),
    ]
