# Generated by Django 5.0.6 on 2024-09-04 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0090_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutritionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nutritionistAssesment', models.TextField()),
                ('nutritionistDiagnosis', models.TextField()),
                ('nutritionistDate', models.CharField(max_length=50)),
                ('nutritionistRecommendations', models.TextField()),
                ('updatedBy', models.EmailField(max_length=254)),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioData.member')),
            ],
        ),
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('psychologistAssesment', models.TextField()),
                ('psychologistDiagnosis', models.TextField()),
                ('pschologistDate', models.CharField(max_length=50)),
                ('psychologistRecommendations', models.TextField()),
                ('updatedBy', models.EmailField(max_length=254)),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioData.member')),
            ],
        ),
    ]
