# Generated by Django 5.0.6 on 2024-09-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioData', '0091_nutritionist_psychologist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psychologist',
            old_name='pschologistDate',
            new_name='psychologistDate',
        ),
    ]
